[window]
padding = { x = 10, y = 10 }
dynamic_title = false
decorations = "Full"
dynamic_padding = true
opacity = 1

[font]
normal = { family = "Source Code Pro", style = "SemiBold" }
italic = { family = "Source Code Pro", style = "SemiBold Italic" }
bold = { family = "Source Code Pro", style = "Bold" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
size = 13

[selection]
save_to_clipboard = true
