# More info at https://github.com/Canop/bacon
summary = false
wrap = true
reverse = true
grace_period = "10ms"
help_line = false
show_changes_count = true
watch = ["crates", "queries"]
# on_change_strategy = "wait_then_restart"
on_change_strategy = "kill_then_restart"

[jobs.test]
command = [
  "cargo",
  "test",
  "--color",
  "always",
  "--quiet",
  "--",
  "--nocapture",
  "--color",
  "always",
]
apply_gitignore = false
allow_warnings = true
need_stdout = true

[keybindings]
ctrl-d = "scroll-pages(1)"
ctrl-u = "scroll-pages(-1)"
b = "toggle-backtrace"
esc = "back"
g = "scroll-to-top"
j = "scroll-lines(1)"
k = "scroll-lines(-1)"
o = "toggle-raw-output"
q = "quit"
shift-g = "scroll-to-bottom"
w = "toggle-wrap"
f = "scope-to-failures"
p = "pause"
shift-p = "unpause"
