summary = true
wrap = true
reverse = false
export_locations = false


[keybindings]
q = "quit"
s = "toggle-summary"
w = "toggle-wrap"
ctrl-t = "toggle-backtrace"
o = "toggle-raw-output"
ctrl-d = "scroll-pages(-1)"
ctrl-u = "scroll-pages(1)"
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
k = "scroll-lines(-1)"
j = "scroll-lines(1)"
