edition = "2021"
unstable_features = true
format_macro_bodies = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
merge_derives = true
merge_imports = true
reorder_imports = true
reorder_modules = true
# reorder_struct_fields = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
condense_wildcard_suffixes = true
