edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
space_after_colon = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_exprs = true
reorder_impl_items = true
unstable_features = true
wrap_comments = true
